name: Triggered Workflow

on:
  repository_dispatch:
    types: [custom-event]  # Use a unique event type name, like "custom-event"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, this is a triggered build!"
